# Setup
name: Alexander Trost
paginate: 5
paginate_path: "/blog/page:num/"
url: "http://alexandertrost.com"

# Assets
sass:
sass_dir:     _sass
style:        :compressed
  
# Build settings
markdown:       kramdown
